config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  post "/events/web_push", "events#web_push"
  post "/events/mobile_push", "events#mobile_push"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :event_type, presence: true
  enum event_type: { web_push: 0, mobile_push: 1 }

  after_commit :send_email_for_mobile_push, if: :mobile_push_event?

  private

  def mobile_push_event?
    event_type == 'mobile_push'
  end

  def send_email_for_mobile_push
    iterable_service = IterableIoService.new(ENV["iterable_io_api_key"])
    iterable_service.send_email(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :initialize_iterable_io_service

  def web_push
    create_event(:web_push)
    begin
      @iterable_io_service.create_web_push_event(@user, @event)
    rescue FailedToCreateEventException => err
      puts err.to_s
    end
  end

  def mobile_push
    create_event(:mobile_push)
    begin
      @iterable_io_service.create_mobile_push_event(@user, @event)
    rescue FailedToCreateEventException => err
      puts err.to_s
    end
  end

  private

  def initialize_iterable_io_service
    puts ENV["iterable_io_api_key"]
    @iterable_io_service = IterableIoService.new(ENV["iterable_io_api_key"])
  end

  def create_event(event_type)
    @user = current_user
    @event = @user.events.create({ name: event_type, event_type: event_type })
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>
  Home Page
  <% if user_signed_in? %>
    <div> Welcome <%= current_user.email %> </div>
    <%= button_to 'Event A', events_web_push_path(current_user), method: :post %>
    <%= button_to 'Event B', events_mobile_push_path(current_user), method: :post %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to "Sign in", new_user_session_path %>
  <% end %>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IterableApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>